### PR TITLE
Sparrow tests for diff-so-fancy tool

### PR DESCRIPTION
**Pull request by melezhik**
Hi guys! I've noticed you use bats for tests. Are you satisfied with it? Alternatively  this is how tests might be achieved by Sparrow framework. Features of possible interest are:

* checking against Perl5 regexps
* checking in sequences of lines (LineA,LineB,LineC so on  - see story.check file )
* Under the hood it's still Bash scripts + check files, so it's pretty simple 

However if you're pretty satisfied with Bats - that's ok, just close this request.

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
I'm really not sure what this offers us over what we already have. I'm pretty happy with `bats`.

**Comment by melezhik** [comment]
Hi! Probably you don't need but I coils find regexp checks. Also writtIng tests on Outthentic requires much less code. Also **much more detailed and accurate checks** of output are possible over those with bats. I suppose all of this can be of immense value for testing such a tools as parsers generating complex unstructured output. Imho this is where Outthentic seems more competitive.

**Comment by scottchiefbaker** [comment]
I appreciate the effort, but I'm pretty happy with bats right now. I will look in to this more for future releases.

**Comment by melezhik** [comment]
Hi @scottchiefbaker , sure. Let me know when you want to come back and consider this tool, I be glad to help you!

**Pull request closed without merging**
