### PR TITLE
Update Arch Linux package URL in README.md

### PR DESCRIPTION
**Pull request by felixonmars**
The old URL returns 404 now.

### CODE REVIEW

**Comment by OJFord** [comment]
Thanks!

**Review by OJFord — APPROVED** [review]

**Comment by scottchiefbaker** [comment]
I have no problem with this commit and am happy to merge it. [Pull requests](https://github.com/so-fancy/diff-so-fancy#contributing) should target the `next` branch however. If you update this to hit that branch I'll merge it.

**Comment by OJFord** [comment]
@scottchiefbaker FYI I've changed the default branch to `next` so that this stops happening. It's also necessary for this readme change to actually appear in the rendered readme when people navigate to the repo (and don't change the branch, because why would they) without also updating `master` too.

**Comment by felixonmars** [comment]
I actually didn't know that I could change the target branch right in this PR. Thanks!

**Pull request merged**
