### PR TITLE
Rework file permission headers

### PR DESCRIPTION
**Pull request by scottchiefbaker**
This addresses #100

### CODE REVIEW

**Comment by paulirish** [comment]
I'm seeing the `diff --git` line in my output with this patch:
image

**Comment by scottchiefbaker** [comment]
Interesting... your diff output doesn't have `a/.bashrc` or `b/.bashrc` on it like mine does. I just updated the pull request to handle both types.

**Comment by paulirish** [comment]
@scottchiefbaker true. once i found `git config --global diff.noprefix true` i've been loving it. :)  But ideally i don't need it when using diff-so-fancy.

**Comment by paulirish** [comment]
@scottchiefbaker as you can see i just added a test for that one. :)

**Comment by paulirish** [comment]
ah so did you. but i added a fixture that starts with noprefix output. so between the two, we're good. ;)

**Pull request merged**
