### PR TITLE
test/diff-highlight: avoid word splitting

### PR DESCRIPTION
**Pull request by williamboman**
Looked a bit scary as-is

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
Just some basic clean up stuff? @stevemao this looks harmless to me, what do you think?

**Comment by stevemao** [comment]
What linter are you using @williamboman ?
@paulirish I roughly remember we were going to use a linter for bats?

**Comment by williamboman** [comment]
> What linter are you using @williamboman ?

None.

**Comment by scottchiefbaker** [comment]
This is harmless, and it's been open for a while. I'm going to merge this, you can flog me later if you don't like it.

**Pull request merged**
