### PR TITLE
Add perlcritic to Travis

### PR DESCRIPTION
**Pull request by maxnordlund**
This is a first stab at #118. Sorry for the noise, but it's hard to debug this without running it on Travis.

### CODE REVIEW

**Comment by maxnordlund** [comment]
OK, nice it's running on Travis and fails as it's supposed to. I hope this helps :)

**Comment by scottchiefbaker** [comment]
Perl critic can be VERY critical. When I first implemented Perl critic stuff I had to turn the level down so it wasn't complaining about everything. Perl critic is good, but it's OVERLY cautious, and not realistic. I think we had to set it to 4 (stern) for it to be worthwhile when I did it at:

http://perlcritic.com/

Can we modify this test to use a more realistic level?

**Comment by maxnordlund** [comment]
Yeah, you can add a config, but since I don't know what you need I figured you tell me.

**Comment by scottchiefbaker** [comment]
Looking at the errors Perl Critic found makes me cringe a little:

```    
I/O layer ":utf8" used at line 9, column 1.  Use ":encoding(UTF-8)" to get strict validation.  (Severity: 5)
```
OK this is fixable.

```
Use IO::Interactive::is_interactive() instead of -t at line 272, column 6.  See page 218 of PBP.  (Severity: 5)
```
I'm not going to require a third party module JUST for this one silly check. That would make installation a lot more complex.

```
Warnings disabled at line 9, column 1. See page 431 of PBP. 
```
This is by design, and part of #168, so we're not going to fix this

```
Subroutine "get_less_charset" does not end with "return" at line 267, column 1. See page 197 of PBP. 
```
Ok this one I will fix... it's trivial

The last three are all:
```
Always unpack @_ first at line...
```
which I don't understand, because that's exactly what we're doing. I'm guessing it just doesn't like our formatting?

**Comment by scottchiefbaker** [comment]
I discussed this with the experts on #perl and the consensus is that the default Perl critic rules do not reflect real world, modern Perl. The groups things that using this theme for Perl critic is much more useful and sane: https://metacpan.org/pod/Perl::Critic::Freenode

Can you investigate if that's something we can enable and use on TravisCI? When I run it locally we look good:

```
bakers@yellow(~/github/diff-so-fancy)
:perlcritic --theme freenode lib/diff-so-fancy.pl
lib/diff-so-fancy.pl source OK
```

**Comment by scottchiefbaker** [comment]
I spent the last hour trying to get TravisCI to work with cpanm on OSX and it's not happening. Here is my updated config:

https://github.com/scottchiefbaker/diff-so-fancy/blob/travis/.travis.yml

It does work and run Perl Critic using the more sane them on Linux just fine. I may just set the PC tests to only run on Linux. Thoughts?

**Comment by maxnordlund** [comment]
I've added you as an collaborator to make this easier. Yeah, I'll take a look right away. I guess running perlcritic just on Linux isn't so bad since it should just report the same errors on all platforms. This also means it can run on just Travis.

**Comment by scottchiefbaker** [comment]
Perl Critic itself SHOULD run on OSX just fine. Travis has their OSX locked down pretty well, so it doesn't easily install modules. It may not be worth the time/energy.

Don't let me discourage you if you want to try to get it working though.

**Comment by maxnordlund** [comment]
After fighting with inline if statements for a while, I realized that the OSX image was way old. So by upgrading it, we upgrade perl and all is good in wonderland. The brew installed perl didn't seem to be picked up by Travis, so I'll try without it.

**Comment by maxnordlund** [comment]
Scratch that, it didn't work so I'll revert to installing perl again. Maybe it's just in before install it didn't seem to work? Anyway, this should be fine since it's how https://travis-ci.org/so-fancy/diff-so-fancy/jobs/137891671 was setup.

**Comment by maxnordlund** [comment]
OK, it's finally behaving. There were a few tricks needed, as written in the commit message. First use a newer version of OSX, then manually install _both_ `perl` and `cpanm`, and lastly for whatever reason, `mkdir -p ~/perl5` is needed or it will explode.

@scottchiefbaker I think this is good to go now.

**Comment by scottchiefbaker** [comment]
I see it's set as generic now, instead of Perl? Will the affect our ability to test on different versions of Perl? I'm thinking older versions may be more inclined to complain about things, so it would be nice to test against older Perls.

**Comment by maxnordlund** [comment]
You can add more in the build matrix, and maybe you can tweak it further down the line, but if I didn't do this it started two 5.18 Linux builds.

**Comment by maxnordlund** [comment]
I can try one thing though, which might work, but I had a lot of trouble making OSX behave as you I'm sure you know.

**Comment by maxnordlund** [comment]
This seems to make the build matrix better, let us see if OSX wants to play ball.

**Comment by maxnordlund** [comment]
Ah yeah, it's a go time for this PR, don't you think so?

**Comment by scottchiefbaker** [comment]
I see... so we can test against diff versions of Perl on Linux, but on OSX it's the installed system one. I'm OK with that, OSX is a pain. If you can add Perl 5.24, 5.22, and 5.20 to the list I'll land this.

**Comment by maxnordlund** [comment]
Done.

**Pull request merged**
