### PR TITLE
re-enable shellcheck on CI

### PR DESCRIPTION
**Pull request by paulirish**
it was failing on circleCI: https://circleci.com/gh/so-fancy/diff-so-fancy/404
and just not enabled on travis

So i've flipped it back on in the config, included report-bug.sh and fixed the errors there.

Now we're green on all our CI. \o/

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
I'm pretty sure I disabled this... we don't have any .sh files anymore, do we need to try and spellcheck them?

**Comment by stevemao** [comment]
@scottchiefbaker I think we can just remove `shellcheck`

**Comment by paulirish** [comment]
well it's there for report-bug.sh now. and I did fix a number of style issues that seem worthwhile.

i think having it present to increase confidence in our bug reporting flow is worth it.

**Comment by scottchiefbaker** [comment]
@paulirish I totally forgot about the `report-bug.sh` good call. I'll merge this.

**Pull request merged**
