### PR TITLE
Add pro-tip about hg diff

### PR DESCRIPTION
**Pull request by srsudar**
As requested on #186.

LMK if you want some style changes, or feel free to edit before merging.

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
This looks good to me. Pull Requests should target the [next branch](https://github.com/so-fancy/diff-so-fancy#contributing). Update this to target `next` and I'll land it.

**Comment by srsudar** [comment]
I forgot a variable in the command. It should terminate with `$@` to apply other command line arguments (to allow `hg diff -r foo` rather than always forcing `hg diff`).

It should be:

```
diff = !HGPLAIN=1 $HG diff --pager=on --config pager.pager=diff-so-fancy $@
```

I'm surprised to see that this PR has some additional commits merged into it. Should I update my branch and apply it to the PR, or should I create new PR with the fix?

**Comment by scottchiefbaker** [comment]
You must have done a `git pull` which pulled in the other commits from `next`. Try doing a `git fetch upstream` and then `git rebase next` to clean up the PR. 

Once the PR is clean I'll merge it.

**Comment by srsudar** [comment]
Everything I did made this worse. I'm going to open a clean PR and spend some time in the shame cube.

**Pull request closed without merging**
