### PR TITLE
Properly remove the right number of leading columns in a three way merge

### PR DESCRIPTION
**Pull request by scottchiefbaker**
Test is also included so we'll know if we break it in the future.

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
One thing I changed was I combined `strip_leading_indicators` and `strip_first_column`. I can't think of a use case where we'd want to remove the pluses and minus indicators and not ALSO that first column that's just a space. 

This should also speed it up a bit because it's one less iteration over the file.

**Comment by paulirish** [comment]
Over in #126 i had a few examples:

git show 74804e377
git diff 91bc769c02 59aebbd379

Can you verify these diffs are showing what you'd expect? At first glance, I'm not seeing what I thought we'd show.

**Comment by scottchiefbaker** [comment]
`git show 74804e3` looks perfect

`git diff 91bc769 59aebbd` includes some leading `+` and `-` because those are actually part of the body of the diff. I think this is correct behavior.

`cat test/fixtures/complex-hunks.diff | diff-so-fancy` will give you a good idea of what we're stripping off. 

The *only* caveat to this is that my detection assumes the same indent level (three-way vs two-way merge) for the entire diff. So **if** it's possible that part of the diff is two way and part is three-way this will probably not remove the correct amount. I don't know three-way merges well enough to know if this is a real world scenario or not.

**Comment by scottchiefbaker** [comment]
Any updates on this?

**Comment by paulirish** [comment]
merged! :D

**Comment by paulirish** [comment]
sorry for the delay. @scottchiefbaker in these sort of cases, i'm pretty comfortable with you merging on your own.

**Pull request merged**
