### PR TITLE
Fixing horizontal rules not displaying correctly

### LINKED ISSUE #72: Horizontal rules not displaying correctly.
Please see the image. I'm using the Solarized Dark xterm-256color theme from https://github.com/mathiasbynens/dotfiles

diff-so-fancy

### PR DESCRIPTION
**Pull request by pauley-unsaturated**
- closes #72

### CODE REVIEW

**Comment by pauley-unsaturated** [comment]
There is a kludge in here ( 4 '+'s and '-'s ).  I think something in the RE is eating a + character, but I can't find it.

**Comment by davidteren** [comment]
Tested and this fixes the issue. Thanks. :+1:

**Comment by stevemao** [comment]
merged 3db8bcb3b5d7200d09fc17fb53ff7405b57db3ec
Thanks @pauley-unsaturated :)

**Comment by paulirish** [comment]
I just updated to master and I'm good too.

**Comment by pauley-unsaturated** [comment]
:100: :rainbow:

**Pull request closed without merging**
