### PR TITLE
Don't error out if we don't have a filename

### LINKED ISSUE #137: Failed to parse this diff, error is fileparse(): need a valid pathname
```diff
diff -r 62e478a3f1c8 -r 47aeb87ce9cd doc/manual.xml.head
--- a/doc/manual.xml.head
+++ b/doc/manual.xml.head
@@ -8352,7 +8352,7 @@
 <row><entry>-a</entry><entry>attach a file to a message</entry></row>
 <row><entry>-b</entry><entry>specify a blind carbon-copy (BCC) address</entry></row>
 <row><entry>-c</entry><entry>specify a carbon-copy (Cc) address</entry></row>
-<row><entry>-d</entry><entry>log debugging output to ~/.muttdebug0 if mutt was complied with +DEBUG; it can range from 1-5 and affects verbosity (a value of 2 is recommended)</entry></row>
+<row><entry>-d</entry><entry>log debugging output to ~/.muttdebug0 if mutt was compiled with +DEBUG; it can range from 1-5 and affects verbosity (a value of 2 is recommended)</entry></row>
 <row><entry>-D</entry><entry>print the value of all Mutt variables to stdout</entry></row>
 <row><entry>-E</entry><entry>edit the draft (-H) or include (-i) file</entry></row>
 <row><entry>-e</entry><entry>specify a config command to be run after initialization files are read</entry></row>
```

colordiff can do with it, but diff-so-fancy fails with:

```
Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/core_perl/File/Basename.pm line 341, <> line 14.
fileparse(): need a valid pathname at /usr/share/diff-so-fancy/diff-so-fancy.pl line 74.
```

### PR DESCRIPTION
**Pull request by scottchiefbaker**
This should fix #137

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
Officially we only support `git diff` output. We should at least not error out on standard diff format.

**Comment by stevemao** [comment]
Thanks @scottchiefbaker , is there a way to add a test for this?

**Comment by scottchiefbaker** [comment]
@stevemao sure... What exactly are we testing? This specific diff format outputs something?

**Comment by stevemao** [comment]
You already added one :)

**Comment by scottchiefbaker** [comment]
If this does what you want go ahead and merge it. I'll work in reading stuff from the gitconfig next.

**Comment by stevemao** [comment]
Thanks @scottchiefbaker !

**Comment by paulirish** [comment]
yeah looks very cool.

**Pull request merged**
