### PR TITLE
add a test for #233

### PR DESCRIPTION
**Pull request by benoit-pierre**
Check the first column is correctly stripped when a hunk has no comma.

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
Just so I understand... we're checking that line 5 says "after"? The logic here being, if there was that regexp error it would drop the after down a couple lines and this test would fail?

**Comment by benoit-pierre** [comment]
Here is the result of running the test without the fix:
```
 ✗ Correctly handle hunk definition with no comma
   (from function `assert_line' in file test/test_helper/bats-assert/src/assert.bash, line 477,
    in test file test/diff-so-fancy.bats, line 96)
     `assert_line --index 5 "after"' failed

   -- line differs --
   index    : 5
   expected : after
   actual   : +after
   --
```

**Comment by benoit-pierre** [comment]
I could check line 4 too, for completeness.

**Comment by scottchiefbaker** [comment]
Your test for line 5 should be enough. Thanks for doing this!

**Pull request merged**
