### PR TITLE
This is my first attempt at reading items from ~/.gitconfig

### PR DESCRIPTION
**Pull request by scottchiefbaker**
This should address #69 and #129 

I don't think this is final, but it's ready for testing. We should probably discuss naming, and what section of the gitconfig we want to use. By default all options are enabled (like they were previous to this commit), but they can be turned *off* with the following commands:

```
git config --unset --global diff-so-fancy.markEmptyLines
git config --unset --global diff-so-fancy.changeHunkIndicators
git config --unset --global diff-so-fancy.stripLeadingSymbols
```
    
```
git config --bool --global diff-so-fancy.markEmptyLines false
git config --bool --global diff-so-fancy.changeHunkIndicators false
git config --bool --global diff-so-fancy.stripLeadingSymbols false
```

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
It should be noted that I've been dog fooding this for several weeks now without issue.

**Comment by paulirish** [comment]
Is ANSI reveal yours? If so then it can be in lib
Also thinking that we could split the gitconfig methods into a config.pl
Otherwise this is looking Clean. 

And yah I think we could start bikeshedding the names. :)

**Comment by scottchiefbaker** [comment]
Yes ANSI reveal is mine... I'll probably release it separately later, so I left it in third party so it's more "standalone" and not d-s-f specific.

**Comment by scottchiefbaker** [comment]
This has been working well for me. Any thoughts on if we're ready to merge this?

@stevemao, @paulirish, @blueyed

**Comment by blueyed** [comment]
@scottchiefbaker 
My Perl foo is very low - sorry, but the idea is good!

Just a thought: it would be useful to easily disable d-s-f.
Currently I am using things like `gdraw='git -c pager.diff="$(git config core.pager)" diff'` to bypass it.
Bypassing will be always useful in case you want to copy'n'paste some diff hunk.

**Comment by stevemao** [comment]
@blueyed https://github.com/so-fancy/diff-so-fancy#opting-out

**Comment by stevemao** [comment]
@scottchiefbaker I don't really get [this comment](https://github.com/so-fancy/diff-so-fancy/issues/129#issuecomment-197455815) yet... but if it works well feel free to merge this.

**Comment by blueyed** [comment]
@stevemao 

> git --no-pager diff

Thanks!
Although that cannot be applied/used at the end of an existing alias..  so I cannot replace `gd` with `gd --no-pager` when needed, but need to use `git --no-pager diff` instead.  A `gnp` alias might make sense, but still it's hard to transform from the original command..  suggestions?

**Comment by stevemao** [comment]
@blueyed I don't think we should add a flag in this module... Rather, rely on git commands or shell.

**Comment by lavoiesl** [comment]
Tested locally, works perfectly.

**Comment by scottchiefbaker** [comment]
I've been testing this for about three weeks and it's working great. I'm going to merge this, so we can move on to bigger and better things.

**Comment by paulirish** [comment]
lookin sharp!

**Comment by matz3** [comment]
What are the plans for a new release which includes this feature? Any open points/issues?

**Pull request merged**
