### PR TITLE
Suggest configuring for git log as well

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by paulirish** [comment]
my logs dont have diffs within them. do you have them configured as such?

**Comment by alex** [comment]
@paulirish `git log -p` :-)

**Comment by paulirish** [comment]
oh word, that's right..  :)  _(btw hi hi. big fan of all the work you've up to.)_

----------------------

We used to have log included in the config by default, but #42 is what turned the tide.
I think the challenge here is performance and matching user expectations. 

.. Okay I say performance but I just tested things...

```sh
git log -p  | wc -l
#  429169
 git log -p  | diff-so-fancy | less --tabs=1,5 -RFX
# displayed in <130ms
```

That's crazy fast. Same fast performance in the Chromium repo. dayum. (Well done @scottchiefbaker!)

Well in that case, it'd be totally open to adding this back to the recommended configuration. 

Trying it out a little, it seems like the parser has no particular issues with the log. Feels pretty safe.

**Comment by paulirish** [comment]
@scottchiefbaker @stevemao thoughts?

@jamischarles can you explain what lead to #42? do you have a separate pager for log configured?

**Comment by scottchiefbaker** [comment]
If performance is good (it should be), then I don't have a problem with this.

**Comment by stevemao** [comment]
> If performance is good (it should be), then I don't have a problem with this.

I suggest to revert #44

**Comment by paulirish** [comment]
SG.

Yeah I think we've come full circle on the config. so @alex it'd be best to adapt your PR to be close to a revert of https://github.com/so-fancy/diff-so-fancy/pull/44/files

**Comment by jamischarles** [comment]
@paulirish If I recall correctly (it was a while ago) things like `git show` didn't work as expected (just blank I think). Here's my confit for reference: https://github.com/jamischarles/dotfiles/blob/master/gitconfig.sym

**Comment by paulirish** [comment]
@jamischarles gotcha. The project's been rewritten almost completely since then so I wouldn't expect you'd have these challenges again. But we can keep an eye on it.

**Comment by alex** [comment]
@paulirish Ok, I think I got this right.

**Comment by stevemao** [comment]
LGTM

**Pull request merged**
